//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AustOldBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookInfo
    {
        public string bookId { get; set; }
        public string userId { get; set; }
        public byte[] bookImage { get; set; }
        public string bookName { get; set; }
        public string authorName { get; set; }
        public int price { get; set; }
        public string semester { get; set; }
        public string depertment { get; set; }
        public Nullable<int> isLock { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
